enum ActionTypes {
  SUBMIT_REGISTRATION = 'SUBMIT_REGISTRATION',
  SUBMIT_REGISTRATION_SUCCESS = 'SUBMIT_REGISTRATION_SUCCESS',
  SUBMIT_REGISTRATION_ERROR = 'SUBMIT_REGISTRATION_ERROR',
  SUBMIT_AUTHORIZATION = 'SUBMIT_AUTHORIZATION',
  SUBMIT_AUTHORIZATION_SUCCESS = 'SUBMIT_AUTHORIZATION_SUCCESS',
  SUBMIT_AUTHORIZATION_ERROR = 'SUBMIT_AUTHORIZATION_ERROR',
  START_DEAUTHORIZATION = 'START_DEAUTHORIZATION',
  DEAUTHORIZATION_SUCCESS = 'DEAUTHORIZATION_SUCCESS',
  SHOW_DEAUTHORIZATION_ERROR = 'SHOW_DEAUTHORIZATION_ERROR',
}

const {
  SUBMIT_REGISTRATION,
  SUBMIT_REGISTRATION_SUCCESS,
  SUBMIT_REGISTRATION_ERROR,
  SUBMIT_AUTHORIZATION,
  SUBMIT_AUTHORIZATION_SUCCESS,
  SUBMIT_AUTHORIZATION_ERROR,
  START_DEAUTHORIZATION,
  DEAUTHORIZATION_SUCCESS,
  SHOW_DEAUTHORIZATION_ERROR,
} = ActionTypes;

export {
  SUBMIT_REGISTRATION,
  SUBMIT_REGISTRATION_SUCCESS,
  SUBMIT_REGISTRATION_ERROR,
  SUBMIT_AUTHORIZATION,
  SUBMIT_AUTHORIZATION_SUCCESS,
  SUBMIT_AUTHORIZATION_ERROR,
  START_DEAUTHORIZATION,
  DEAUTHORIZATION_SUCCESS,
  SHOW_DEAUTHORIZATION_ERROR,
};
